### ISSUE TITLE
[Bug] After upgrade Merlin to 3006.102.6 can't login

### ISSUE THREAD

**Issue by intelx3** [Vaskivskyi/ha-asusrouter#1111]
### Device model

RT-AX86UPRO

### Firmware version

Merlin  3006.102.6

### Bug details

After upgrade Merlin to 3006.102.6 can't login
Earlier on 3006.102.5 works flawlessly

Tested on release v0.40.1

<img width="768" height="753" alt="Image" src="https://github.com/user-attachments/assets/d18cb40d-34c4-4f6f-8dc5-b055a8aad985" />

<img width="862" height="288" alt="Image" src="https://github.com/user-attachments/assets/a4b76dbb-bd51-4f90-a88a-d64908489d93" />

<img width="438" height="620" alt="Image" src="https://github.com/user-attachments/assets/f34b0260-c5d3-4c43-8406-7ae7ab3eb062" />

**Comment by Suyknow** [comment]
I encountered the same issue as you, but mine didn't happen after a ROUTER update; it happened after a HOME ASSISTANT update.

After analyzing the logs, the AI believes the cause is that the underlying Python libraries are no longer compatible. Specifically:

>>ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error of type '<class 'AttributeError'>' during connection to 192.168.86.1: 'str' object has no attribute 'get'

>The core of the problem is that the asusrouter integration's code cannot correctly parse the data communicating with the router.
>This situation typically occurs after a Home Assistant Core update, where changes to the underlying Python environment or dependency libraries cause the older version of the integration code to become incompatible.

**Comment by Vaskivskyi** [comment]
Hello. This is not related to the FW update, but to the HA 2025.12.2. Please refer to this issue for the info and temporary fixes until HA 2025.12.3 is released https://github.com/Vaskivskyi/ha-asusrouter/issues/1101

**Comment by intelx3** [comment]
My mistake, I correlated it with a router FW update, but in fact same day HA was also updated.
