### ISSUE TITLE
[Bug] 2025.12.2 - Appears to cause integration to break "AttributeError"

### ISSUE THREAD

**Issue by shuntfield** [Vaskivskyi/ha-asusrouter#1101]
### Device model

RT-BE92U

### Firmware version

3.0.0.6.102_38980

### Bug details

```
This error originated from a custom integration.

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:308
integration: AsusRouter (documentation, issues)
First occurred: 22:42:47 (5 occurrences)
Last logged: 22:57:18

Unknown error of type '<class 'AttributeError'>' during connection to `192.168.0.1`: 'str' object has no attribute 'get'
```
Getting this error now appear in the log and also 

```
Logger: homeassistant.config_entries
Source: config_entries.py:761
First occurred: 22:39:06 (1 occurrence)
Last logged: 22:39:06

Error setting up entry 192.168.0.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 349, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 251, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.13/site-packages/asusrouter/asusrouter.py", line 203, in async_connect
    return await self.async_get_identity() is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/asusrouter.py", line 293, in async_get_identity
    self._identity = await collect_identity(
                     ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/identity.py", line 126, in collect_identity
    endpoints, onboarding = await _check_endpoints(api_query)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/identity.py", line 230, in _check_endpoints
    onboarding = process_onboarding(
                 ~~~~~~~~~~~~~~~~~~^
        read_onboarding(contents[Endpoint.ONBOARDING])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).get(AsusData.AIMESH, {})
    ^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/onboarding.py", line 47, in process
    for node in [process_aimesh_node(device)]
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/onboarding.py", line 98, in process_aimesh_node
    level = safe_int(data.get("level", "0"))
                     ^^^^^^^^
AttributeError: 'str' object has no attribute 'get' 
```

Seemed to be working fine before updating to 2025.12.2.

Tried restarting the httpd from SSH, and deleting and reinstalling the integration. I am using 0.40.1

Hope this helps

**Comment by Vaskivskyi** [comment]
Hey. Fixing this now. 2025.12.2 has bumped the backend library. Unfortunately, it looks like automatic tests did not catch this issue. I will make sure the test base is extended to avoid this in the future.

**Comment by jepajo** [comment]
I have the same issue using Zenwifi bt8.

**Comment by Alfamonk** [comment]
Same problem for me, using GT-BE98.

**Comment by kelddamsbo** [comment]
Same problem here too, also using GT-BE98

**Comment by MikedaSpike** [comment]
Same issue here. Although it can connect to my two mesh routers ZenWiFi AX, it cannot connect to the main router RT-AXE7800.

**Comment by wluca** [comment]
same issue here RT-BE88U

**Comment by rholligan** [comment]
Same issue for me, appeared around 10:00 UK today (which I think coincided with an update to HA Core 2025.12.2). ZenWiFi AX (RT-AX95Q), Firmware: 3.0.0.4.388_24710-gf758fa3, Integration Version 0.40.1

**Comment by binary100100** [comment]
2025-12-09 07:53:11.215 WARNING [homeassistant.loader] Found custom integration: asusrouter

2025-12-09 07:53:33.143 ERROR [homeassistant.config_entries] 
Error setting up entry <router_ip> for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 349, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 251, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.13/site-packages/asusrouter/asusrouter.py", line 203, in async_connect
    return await self.async_get_identity() is not None
  File "/usr/local/lib/python3.13/site-packages/asusrouter/asusrouter.py", line 293, in async_get_identity
    self._identity = await collect_identity(
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/identity.py", line 126, in collect_identity
    endpoints, onboarding = await _check_endpoints(api_query)
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/identity.py", line 230, in _check_endpoints
    onboarding = process_onboarding(
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/onboarding.py", line 47, in process
    for node in [process_aimesh_node(device)]
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/onboarding.py", line 98, in process_aimesh_node
    level = safe_int(data.get("level", "0"))
AttributeError: 'str' object has no attribute 'get'

Primary router: ASUS GT-BE98 Pro
Primary firmware: 3.0.0.6.102_39112

AiMesh nodes and firmware versions:
- RT-AX3000 → 3.0.0.4.388_25277
- RT-AX1800S → 3.0.0.4.386_69155
- RT-AXE7800 → 3.0.0.4.388_25204
- RT-BE88U → 3.0.0.6.102_39112

AsusRouter HACS version: 0.40.1
Home Assistant Core:
- Works in 2025.12.1
- Fails in 2025.12.2 with the above traceback

**Comment by Vaskivskyi** [comment]
The issue is found, localised and fixed in the new backend library 1.21.3.

Until the bugfix is released in HA Core (which will provide an update also for users of asusrouter), there are two options:

1. Manually install the newer backend (if you can run a pip install command, e.g. through Docker terminal inside your container) using

    `pip install asusrouter==1.21.3`

2. Roll back to 2025.12.1 and wait for 2025.12.3 to be released (if the corresponding PR https://github.com/home-assistant/core/pull/158492 will be added to this minor release, which I expect)

**Comment by yuejon** [comment]
I installed 1.21.3 backend and it fixed the issue for me. Thanks for the quick turnaround.

**Comment by baulaergrungim** [comment]
Is there a way to do it with supervisor mode? I have terminal addon and studio core

**Comment by Impair1980** [comment]
Perfect! THX!

<img width="1399" height="519" alt="Image" src="https://github.com/user-attachments/assets/d790f19a-f064-4b87-8dcd-610213a711a1" />

**Comment by nonsholant10** [comment]
What seems to have worked for me is using the File Editor to go to "/homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the _pip_ command) & changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_. Then, I rebooted HA & AsusRouter works as it did before.

Just posting this info for anyone that might've struggled with _pip_ as I did.

**Comment by jdeath** [comment]
> changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_.

Worked perfectly. Thanks!

**Comment by binary100100** [comment]
> What seems to have worked for me is using the File Editor to go to "/homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the _pip_ command) & changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_. Then, I rebooted HA & AsusRouter works as it did before.
> 
> Just posting this info for anyone that might've struggled with _pip_ as I did.

Oddly enough, that worked for me too.
Thanks!

**Comment by shuntfield** [comment]
> What seems to have worked for me is using the File Editor to go to "/homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the _pip_ command) & changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_. Then, I rebooted HA & AsusRouter works as it did before.
> 
> Just posting this info for anyone that might've struggled with _pip_ as I did.

Yup used this method too and back working Thanks!

**Comment by Voldemort112** [comment]
> What seems to have worked for me is using the File Editor to go to "/homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the _pip_ command) & changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_. Then, I rebooted HA & AsusRouter works as it did before.
> 
> Just posting this info for anyone that might've struggled with _pip_ as I did.

Worked perfectly. Thanks!

**Comment by Dwokfur** [comment]
> What seems to have worked for me is using the File Editor to go to "/homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the _pip_ command) & changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_. Then, I rebooted HA & AsusRouter works as it did before.
> 
> Just posting this info for anyone that might've struggled with _pip_ as I did.

Excellent solution until 12.3 arrives!

**Comment by charl3y15** [comment]
> > What seems to have worked for me is using the File Editor to go to "/homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the _pip_ command) & changing the value on the requirements line (line 11 for me) to the aforementioned _1.21.3_. Then, I rebooted HA & AsusRouter works as it did before.
> > Just posting this info for anyone that might've struggled with _pip_ as I did.
> 
> Excellent solution until 12.3 arrives!

didn't work for me unfortunately :(

**Comment by MEKadan** [comment]
Hi guys, @Vaskivskyi ,

For me I did not get any error messages with updates 2025.12.2. and earlier, but after updating today to 2025.12.3 I get the same error then others.

From settrings-> Devices& services/ Integrations

<img width="378" height="250" alt="Image" src="https://github.com/user-attachments/assets/dba2032d-de23-4b90-8416-e01e377e6417" />

From log:


```
Logger: homeassistant.config_entries
Source: config_entries.py:761
First occurred: 15:52:13 (4 occurrences)
Last logged: 15:56:39
Error setting up entry 192.168.1.1 for asuswrt

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/__init__.py", line 18, in async_setup_entry
    await router.setup()
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/router.py", line 231, in setup
    await self._api.async_connect()
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/bridge.py", line 248, in async_connect
    await self._get_label_mac()
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/bridge.py", line 280, in _get_label_mac
    label_mac = await self._get_nvram_info("LABEL_MAC")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/bridge.py", line 270, in _get_nvram_info
    info = await self._api.async_get_nvram(info_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioasuswrt/asuswrt.py", line 449, in async_get_nvram
    regex = _NVRAM_REGEX.format(item)
KeyError: '<item>'
```

From above I noticed a workaround:

` ... using the File Editor to go to  /homeassistant/custom_components/asusrouter/manifest.json" (since I couldn't use the pip command) & changing the value on the requirements line (line 11 for me) to the aforementioned 1.21.3. Then, I rebooted HA & AsusRouter works as it did before.`

I do not know for sure, how Asuswrt was installed in a first place in my case, because it was a long time ago, but I do not have asusrouter -folder in my custom_components. Nor does it exist in HACS  or HA addons.

**Comment by Vaskivskyi** [comment]
@MEKadan, hello

The integration in your snapshot and your log is AsusWRT integration built into Home Assistant and has nothing to do with AsusRouter custom component (which is this repository and discussion).

For the issue with AsusWRT inside Home Assistant at version 2025.12.3, please refer to https://github.com/home-assistant/core/issues/158822 in the HA repository.

This is a responsibility of a different maintainer who might help you there. Unfortunately, I cannot help with this

**Comment by rivica-web** [comment]
Hello,
I still have a problem with 2025.12.3 but asuswrt is working

![Image](https://github.com/user-attachments/assets/376260d4-afcc-4b0e-abdb-14b461a1375b)
Logger: homeassistant.config_entries
Source: config_entries.py:761
First occurred: 1:14:51 PM (2 occurrences)
Last logged: 1:17:28 PM

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 453, in setup
    await self._init_sensor_coordinators()
  File "/config/custom_components/asusrouter/router.py", line 853, in _init_sensor_coordinators
    available_sensors = await self.bridge.async_get_available_sensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 378, in async_get_available_sensors
    SENSORS: await self._get_sensors_modern(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        AsusData.WIREGUARD_CLIENT
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/asusrouter/bridge.py", line 672, in _get_sensors_modern
    data = await self.api.async_get_data(datatype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/asusrouter.py", line 896, in async_get_data
    processed = process(
        endpoint,
    ...<3 lines>...
        self._identity.wlan,
    )
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/__init__.py", line 194, in process
    result = submodule.process(data)
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/hook.py", line 155, in process
    vpnc, vpnc_clientlist = process_vpnc(data)
                            ~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asusrouter/modules/endpoint/hook.py", line 540, in process_vpnc
    vpnc[vpnc_id].update(
    ~~~~^^^^^^^^^
KeyError: 0

**Comment by Vaskivskyi** [comment]
@rivica-web please, refer to #1120
