### ISSUE TITLE
[Bug] Error: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by tdbegley28** [Vaskivskyi/ha-asusrouter#1103]
### Device model

RT-AX86U

### Firmware version

3004_388.4_0

### Bug details

Attempting to install the integration. I enter the IP of my router 192.168.50.1 then the next page I add my credentials. Leave the port at 0 and enable SSH. When I press ok I get "Unknown Error" and the following in the log.

`Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:308
integration: asusrouter ([documentation](https://asusrouter.vaskivskyi.com/), [issues](https://github.com/Vaskivskyi/ha-asusrouter/issues))
First occurred: 12:56:31 (4 occurrences)
Last logged: 13:54:55

Unknown error of type '<class 'AttributeError'>' during connection to `192.168.50.1`: 'str' object has no attribute 'get'`

**Comment by michaeltlp** [comment]
I am facing the same connectivity issue with my XT8 after upgrading to  2025.12.2.

**Comment by weersing** [comment]
Yep the same issue with my AC2900 after upgrading to 2025.12.2

**Comment by pr0fetul** [comment]
Hi,
Same error - RT-BE88U on HA 2025.12.2. Until HA 2025.12.02 it worked ok.

**Comment by mccaffm** [comment]
same issue with RP-AX58, rollback to 2025.12.1 and issue goes away 

assume its this change in 12.2 that has caused it - 

Bump asusrouter to 1.21.1 ([@Vaskivskyi](https://github.com/Vaskivskyi) - [#158192](https://github.com/home-assistant/core/pull/158192))

**Comment by Vaskivskyi** [comment]
Thanks for your reports

Hey. Please follow this issue status https://github.com/Vaskivskyi/ha-asusrouter/issues/1101 to see the latest updates on the issue. I am closing this one since it is a duplicate
