### ISSUE TITLE
[Bug] Unable to add a router in the integration

### ISSUE THREAD

**Issue by mariuszpreiss** [Vaskivskyi/ha-asusrouter#994]
### Device model

GT-AX6000

### Firmware version

3.0.0.6.102_34860-gc346ca4_404-ge7bfb

### Bug details

I have actually a mesh that consists of GT-AX6000 (192.168.15.1) and RT-AX58U (firmware 3.0.0.4.388_25210-gfbda585)
I have an admin user defined as non-default name (so not 'admin') and also SSL enabled (on port 8443 - only https allowed).

When I provide all configuration data (router IP, not name, username, password, port 8443 and SSL checked) I got on top "Uknown error" in the integration configuration pane.
I can see in the router logs that login was successfull, although I'm using another ASUS integration so I'm not 100% sure this is this one (I would like to change the integration since another is not reliable)

```
Sep  7 13:36:59 HTTPD: [LOGIN][https][Web] success (192.168.15.186)
Sep  7 13:37:55 HTTPD: [LOGIN][https][APP] success (192.168.15.76)
Sep  7 13:38:35 HTTPD: [LOGIN][https][APP] success (192.168.15.76)
```

The .186 is my PC, .76 is HA instance
To make sure it does not interfere (since you can be logged in from one PC only) - I loged out on my PC before trying to login via integration.

In the HA core logs, I can see the below, which indicates... incompatibility? or... no idea what

```
Rigistration: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:308
Integration: AsusRouter
[...]

    Unknown error of type '<class 'AttributeError'>' during connection to `192.168.15.1`: 'AsusRouter' object has no attribute 'webpanel'
    Unknown error of type '<class 'asusrouter.error.AsusRouterIdentityError'>' during connection to `192.168.15.1`: ('Failed to collect identity data from the router', None)
```

One thing to note is that SSL cert that Asus configures has a very long validity date (it's valid until 2045 or so which is e.g. causing browsers to raise an alarm) - probably not important though

Any ideas? I checked the support for this device and documentation says "Expected to work", firmware version is >3.0.0.6 and >3.0.0.4 so also should be fine...

**Comment by Vaskivskyi** [comment]
Hello. Let's go step-by-step. I suppose you have integration version 0.40.0, but this error:

```
Unknown error of type '<class 'AttributeError'>' during connection to `192.168.15.1`: 'AsusRouter' object has no attribute 'webpanel'
```

means that the backend library did not update to the correct version. Do you have access to the HA environment? You can try confirming this by running

```
pip show asusrouter
```

The version should be `1.21.0` - this is the backend library, which does all the communications. Since it's probably not the case, you can try to manually update it via

```
pip install asusrouter==1.21.0
```

If you can do these two steps successfully, restart the HA and try setting up your device again.

**Comment by Vaskivskyi** [comment]
P.S. Non-`admin` username, self-signed by router certificate and simultaneous logins to the webpanel should not influence the behaviour - it can work with all those fine

**Comment by mariuszpreiss** [comment]
Thanks for answer @Vaskivskyi 
OK, so I checked and indeed log

```
Sep  7 21:10:51 HTTPD: [LOGIN][https][APP] success (192.168.15.76)
```

is related to your integration - so in theory it logs in OK.

This is hassio running on a VM on QNAP, so I can't run pip commands, sorry :(

Indeed I'm using 0.40.0 version of an integration and newest HA (core and OS) - everything is basically updated

I checked manifest.json for this integration and it looks like so

```
{
  "domain": "asusrouter",
  "name": "AsusRouter",
  "codeowners": ["@vaskivskyi"],
  "config_flow": true,
  "documentation": "https://asusrouter.vaskivskyi.com",
  "integration_type": "hub",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/Vaskivskyi/ha-asusrouter/issues",
  "loggers": ["asusrouter"],
  "requirements": ["asusrouter>=1.21.0"],
  "version": "0.40.0"
}
```

**Comment by seanob86** [comment]
Hi. I also have this issue as well.

`2025-09-08 07:07:18.889 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error of type '<class 'AttributeError'>' during connection to `10.0.0.1`: 'AsusRouter' object ha
s no attribute 'webpanel'`

I upgraded asusrouter to `1.21.0`, but the error still appears, unable to login. 

```
Name: asusrouter
Version: 1.21.0
Summary: API wrapper for communication with ASUSWRT-powered routers using HTTP protocol
Home-page: https://github.com/Vaskivskyi/asusrouter
Author: 
Author-email: Yevhenii Vaskivskyi <yevhenii@vaskivskyi.com>
License-Expression: Apache-2.0
Location: /usr/local/lib/python3.13/site-packages
Requires: aiohttp, urllib3, xmltodict
Required-by: 
```

If I downgrade integration to `0.39.0` I can login and configure the integration. But upgrading introduces the issue again.
I am using the official docker container using `latest` tag, version `2025.9.1`

Third party integrations installed
```
adaptive lighting
bureau of meteorology
dawarich
hacs
ingress
nintendo switch parental controls
bubble card
pi-hole v6 integration
pihole card
samsungtv smart
mushroom
catppuccin theme
```

**Comment by miketarg** [comment]
I have this same issue to

<img width="398" height="578" alt="Image" src="https://github.com/user-attachments/assets/9c7d81a3-f9fa-4c4a-b7c0-0d4618dcd165" />

This error originated from a custom integration.

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:308
integration: AsusRouter (documentation, issues)
First occurred: 11:03:43 AM (1 occurrence)
Last logged: 11:03:43 AM

Unknown error of type '<class 'AttributeError'>' during connection to `192.168.0.2`: 'AsusRouter' object has no attribute 'webpanel'

**Comment by beaver1983467** [comment]
Have the same issue with my RT-AC88U with fw 3.0.0.4.386 48322 after upgrading from 39 to 40.

**Comment by delattre** [comment]
Same issue with RT-AX86U fw 3006.102.5

**Comment by Vaskivskyi** [comment]
This issue is fixed in `0.40.1`
